#cfpr: Create fix pull request (= full repository scan)

pr: none
trigger: none

pool:
  #name: Default
  vmImage: ubuntu-latest

variables:
  JF_GIT_PROJECT: $(System.TeamProject)
  JF_GIT_REPO: 'JFrog-Frogbot-Demo' #$(Build.Repository.Name)
  JF_GIT_BASE_BRANCH: $[ replace(variables['Build.SourceBranchName'], 'refs/heads/', '') ]  # main(マージ先)
  # JF_GIT_BRANCH: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ] # prするブランチ
  # JF_GIT_PULL_REQUEST_ID: $(System.PullRequest.PullRequestNumber) #pr様なのでCFPRには不要。
  JF_GIT_COMMIT: $(Build.SourceVersion)
  JF_GIT_OWNER: 'mikio-seto'
  JF_GIT_PROVIDER: 'github'
  GITHUB_JOB: 'azure-pipeline-job'
  GITHUB_WORKFLOW: 'azure-pipeline-wf'
  JFROG_CLI_LOG_LEVEL: DEBUG


jobs:
  - job:
    displayName: "Frogbot Scan Repository and Fix"
    steps:
       - task: CmdLine@2
         displayName: 'Run frogbot for PR'
         env: 
            JF_URL: $(JF_URL)
            JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)
            JF_GIT_TOKEN: $(JF_GIT_TOKEN)
            # JF_RELEASES_REPO: 'mikios-releases-jfrog-io' #this is when you are DLing frogbot via remote repo.
         inputs:
            script: |
               env # just to check env variables.
               getFrogbotScriptPath=$(if [ -z "$JF_RELEASES_REPO" ]; then echo "https://releases.jfrog.io"; else echo "${JF_URL}/artifactory/${JF_RELEASES_REPO}"; fi)
               curl -fLg "$getFrogbotScriptPath/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh" | sh
               ./frogbot cfpr
