# this is a sample for the PR frogbot scan.
pr: 
 - master
 - main

trigger: none

pool:
  #name: Default
  vmImage: ubuntu-latest

variables:
  JF_GIT_PROJECT: $(System.TeamProject)
  JF_GIT_REPO: 'JFrog-Frogbot-Demo' #$(Build.Repository.Name)?
  JF_GIT_BASE_BRANCH: $[ replace(variables['System.PullRequest.TargetBranch'], 'refs/heads/', '') ]  # main(マージ先)
  JF_GIT_BRANCH: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ] # prするブランチ
  JF_GIT_PULL_REQUEST_ID: $(System.PullRequest.PullRequestNumber) # must be PullRequestNumber for GitHub Integration.
  JF_GIT_COMMIT: $(Build.SourceVersion)
  JF_GIT_OWNER: 'mikio-seto' #Org name of GitHub
  JF_GIT_PROVIDER: 'github' #
  GITHUB_JOB: 'azure-pipeline-job'
  GITHUB_WORKFLOW: 'azure-pipeline-wf'
  JFROG_CLI_LOG_LEVEL: DEBUG
  JF_INCLUDE_ALL_VULNERABILITIES: true


jobs:
  - job:
    displayName: "Frogbot Scan Repository and Fix"
    steps:
       - task: CmdLine@2
         displayName: 'Run frogbot for PR'
         env: 
            JF_URL: $(JF_URL)
            JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)
            JF_GIT_TOKEN: $(JF_GIT_TOKEN)
            # JF_RELEASES_REPO: 'mikios-releases-jfrog-io' #this is when you are DLing frogbot via remote repo.
         inputs:
            script: |
               env # just to check env variables.
               getFrogbotScriptPath=$(if [ -z "$JF_RELEASES_REPO" ]; then echo "https://releases.jfrog.io"; else echo "${JF_URL}/artifactory/${JF_RELEASES_REPO}"; fi)
               curl -fLg "$getFrogbotScriptPath/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh" | sh
               ./frogbot spr

#### SAMPLE for Windows/PowerShell
#       - task: PowerShell@2
#         displayName: 'Download and Run Frogbot by powershell'
#         env:
#            JF_URL: $(JF_URL)
#            JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)
#            JF_GIT_TOKEN: $(JF_GIT_TOKEN)
#            JF_RELEASES_REPO: 'mikios-releases-jfrog-io' #this is when you are DLing frogbot via remote repo.
#         inputs:
#            targetType: 'inline'
#            script: |
#               echo "#####Downloading#####"
#               if ([string]::IsNullOrEmpty($env:JF_RELEASES_REPO)) {
#                   $url = "https://releases.jfrog.io/artifactory/frogbot/v2/[RELEASE]/frogbot-windows-amd64/frogbot.exe"
#                   curl.exe -fLg $url -o frogbot.exe
#                   echo "#####Downloaded from releases.jfrog.io#####"
#               } else {
#                   $url = "${env:JF_URL}/artifactory/${env:JF_RELEASES_REPO}/artifactory/frogbot/v2/[RELEASE]/frogbot-windows-amd64/frogbot.exe"
#                   #curl.exe -fLg -H "Authorization: Bearer $(JF_ACCESS_TOKEN)" $url -o frogbot.exe
#                   Invoke-WebRequest -Uri $url -Headers @{ "Authorization" = "Bearer $(JF_ACCESS_TOKEN)" } -OutFile "frogbot.exe"
#                   echo "#####Downloaded from remote repository#####"
#               }
#               echo "#####Show env#####"
#               ls Env:
#               echo "#####Running frogbot#####"
#               .\frogbot spr
